import '../../public/reset.css'
import RootContainer from '@/component/RootContainer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ background: "#d8ebff" }}>
        <RootContainer>
          <div style={{ position: "absolute", left: 304, top: 90 }}>
            {children}
          </div>
        </RootContainer>
      </body>
    </html>
  );
}