import { color } from '@/styles/color';
import '../../public/reset.css';
import '../styles/global.css';
import Provider from '@/components/Container/RootContainer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ background: color.gray.black }}>
        <Provider>
          <div style={{ display: 'flex', justifyContent: 'center' }}>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
