import RootSidebar from '@/components/RootSidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ display: 'flex' }} >
      <RootSidebar />
      {children}
    </div>
  );
}
