// import '/public/reset.css';
import '@/styles/global.css';
import RootContainer from '@/components/RootContainer';
import { color } from '@/styles/color';

import HeaderContainer from '@/components/HeaderContainer';
import Sidebar from '@/components/Sidebar/Sidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ display: 'flex' }}>
      <Sidebar />
      <RootContainer>{children}</RootContainer>
    </div>
  );
}
